package org.Excption_Handling;

import java.util.Scanner;

public class trycatch {
    public static void main(String[] args) {
        try {
//            meth1();
//            meth2();
//            meth3();
        } catch (Exception e) {
            System.out.println("Excption Handle.java");
        }

    }

    public static void math1() throws Exception{
        Scanner sc = new Scanner(System.in);
        int no = sc.nextInt();
        int ans = 10 / no;

        {
        }
    }
}
